ABACBSAbsSS/urls.py
from django.contrib import admin
from django.urls import path, include


handler403 = 'index.views.handler403'
handler404 = 'index.views.handler404'
handler500 = 'index.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('', include('account.urls', namespace='account')),
    path('', include('abstract.urls', namespace='abstract')),
]

abstract/urls.py
from django.urls import path, include

from . import views

app_name = 'abstract'

urlpatterns = [
    path('abstract/submit/', views.SubmissionView.as_view(), name='submit_abstract'),
    path('abstract/detail/<slug:id>/', views.AbstractDetailView.as_view(), name='abstract_summary'),
    path('abstract/edit/<slug:id>/', views.EditSubmissionView.as_view(), name='edit_abstract'),
    path('abstract/delete/<slug:id>/', views.DeleteSubmissionView.as_view(), name='delete_abstract'),
]

account/urls.py
from django.urls import path, include
from django.contrib.auth import logout

from . import views

app_name = 'account'

urlpatterns = [
    # ------ Login and Logout
    path('orcid/error/', views.orcid_login_error, name="orcid_login_error"),
    path('oauth/', include('social_django.urls', namespace='social'), name="social"),
    path('logout/', logout, name='logout'),
    path('login/orcid/', views.login_with_orcid, name='orcid_login'),
    path('login/staff/', views.staff_login, name='staff_login'),
    path('login/reset/', views.ResetPassword.as_view(), name="reset_password"),

    # ------ Profile
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/settings/', views.EditProfileView.as_view(), name="edit_profile"),
    path('profile/scholarship/', views.submitter.ScholarshipApplicationView.as_view(), name="scholarship_application"),
    path('profile/assign/<slug:id>/', views.assigner.assign_reviewers_view, name="assign_reviewers"),

    path('profile/download/abstracts/', views.chair.DownloadAbstracts.as_view(), name="download_abstracts"),
    path('profile/download/scholarships/', views.chair.DownloadScholarshipApplications.as_view(), name="download_scholarships"),
    path('profile/scholarships/', views.chair.ScholarshipListView.as_view(), name="scholarships"),
]

index/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('demographics/', views.plots, name='plots'),
]

abstract/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.template.loader import render_to_string

from core import mixins

from account.models import UserGroups
from abstract.models import Assignment

from . import models, fields


User = get_user_model()


class AbstractForm(mixins.UserKwargsMixin,
                   mixins.SetUserOnSaveMixin,
                   forms.ModelForm):
    """Basic form for an abstract submission."""
    user_kwarg = 'user'
    user_field = 'submitter'
    
    class Meta:
        model = models.Abstract
        fields = ('title', 'text', 'contribution', 'authors',
                  'author_affiliations', 'keywords', 'categories')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['keywords'] = fields.FlexibleModelMultipleChoiceField(
            klass=models.Keyword,
            to_field_name='text',
            label='Keywords',
            required=True,
            queryset=models.Keyword.objects.all(),
            widget=forms.SelectMultiple(
                attrs={"class": "select2 select2-token-select"}
            ),
            help_text=self.fields['keywords'].help_text,
        )
        self.fields['categories'] = forms.ModelMultipleChoiceField(
            label='Presentation category',
            required=True,
            queryset=models.PresentationCategory.objects.all(),
            widget=fields.CategorySelect(),
            help_text=self.fields['categories'].help_text,
        )
        self.fields['categories'].widget.disabled_choices = [
            category.pk for category
            in models.PresentationCategory.get_closed_categories()
        ]

    def clean_authors(self):
        return '\n'.join([
            x.strip() for x in
            self.cleaned_data.get('authors', '').split('\n')
            if x.strip()
        ])
    
    def clean_author_affiliations(self):
        return '\n'.join([
            x.strip() for x in
            self.cleaned_data.get('author_affiliations', '').split('\n')
            if x.strip()
        ])

    def clean(self):
        cleaned_data = super().clean()
        authors = cleaned_data.get('authors', '')
        author_affiliations = cleaned_data.get('author_affiliations', '')
        if len(authors.split('\n')) != len(author_affiliations.split('\n')):
            self.add_error(
                'authors',
                (
                    'The number of authors must be the same as the number of '
                    'author affiliations. Each author must start on a new line.'
                )
            )
            self.add_error(
                'author_affiliations',
                (
                    'The number of authors affiliations must be the same as '
                    'the number of authors. Each affiliation must start on a '
                    'new line.'
                )
            )
        return cleaned_data
    
    def _save_m2m(self):
        for kw in self.cleaned_data.get('keywords', []):
            kw.save()
        return super()._save_m2m()


class ReviewForm(mixins.ExtraKwargsMixin,
                 mixins.SetFieldsOnSaveMixin,
                 forms.ModelForm):
    """Form filled out by a reviewer which rates an abstract."""
    extra_kwargs = ('reviewer', 'abstract',)
    extra_fields = ('reviewer', 'abstract',)
    
    class Meta:
        model = models.Review
        fields = ('text', 'score_content',
                  'score_contribution', 'score_interest',)


class RejectAssignmentForm(forms.ModelForm):
    """
    Form filled out by a reviewer which rejects an abstract. Requires
    instance to be passed in.
    """
    class Meta:
        model = models.Assignment
        fields = ('rejection_comment',)


class AssingmentForm(mixins.ExtraKwargsMixin, forms.Form):
    """Form to add/remove reviewers to an abstract."""
    extra_kwargs = ('abstract', 'assigner',)

    def label_from_instance(self, obj):
        state = obj.profile.state
        return '{uname} | {name} | {state} | {kws}'.format(
            uname=obj.username,
            name=obj.profile.full_name,
            state='Unknown state' if not state else state.text,
            kws=', '.join([kw.text for kw in obj.profile.keywords.all()]) \
                or 'No keywords',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        reviewers = User.objects.filter(groups__name=UserGroups.REVIEWER.value)
        self.fields['reviewers'] = forms.ModelMultipleChoiceField(
            label='Reviewers',
            help_text="Assign reviewers to or remove from this abstract.",
            required=False,
            queryset=reviewers,
            widget=forms.SelectMultiple(
                attrs={"class": "select2 select2-token-select"},
            )
        )
        if not self.abstract:
            raise AttributeError("`abstract` cannot be None.")
        if not self.assigner:
            raise AttributeError("`reviewer` cannot be None.")

        self.fields['reviewers'].label_from_instance = self.label_from_instance

    def clean_reviewers(self):
        qs = self.cleaned_data.get('reviewers', [])
        reviewer_group = UserGroups.get_group(UserGroups.REVIEWER)
        qs = [u for u in list(qs) if reviewer_group in u.groups.all()]
        return qs
    
    def save(self):
        removed = []
        added = []
        for user in self.abstract.assigned_reviewers:
            if user not in self.cleaned_data.get('reviewers', []):
                removed.append(user)
        for user in self.cleaned_data.get('reviewers', []):
            if user not in self.abstract.assigned_reviewers:
                added.append(user)
                
        for user in removed:
            template_name = "account/assignment_removed.html"
            message = render_to_string(template_name, {
                'abstract': self.abstract,
                'reviewer': user
            })
            user.profile.email_user(
                subject='[ABACBSAbsSS] Assignment removed.',
                message=message,
            )
            if Assignment.objects.filter(
                    abstract=self.abstract, reviewer=user).count():
                assignment = Assignment.objects.get(
                    abstract=self.abstract, reviewer=user)
                if assignment.review:
                    assignment.review.delete()
                assignment.delete()
        
        for user in added:
            Assignment.objects.create(
                reviewer=user, abstract=self.abstract,
                created_by=self.assigner
            )
            template_name = "account/assignment_added.html"
            message = render_to_string(template_name, {
                'abstract': self.abstract,
                'reviewer': user
            })
            user.profile.email_user(
                subject='[ABACBSAbsSS] Assignment added.',
                message=message,
            )
        
        return self.abstract

abstract/views.py
import logging

from django.views.generic import (
    CreateView, UpdateView, DeleteView, DetailView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.contrib import messages
from django.shortcuts import redirect

from account.models import UserGroups
from account.mixins import CompleteProfileRequired, GroupRestrictedView

from core.mixins import CheckClosingDateMixin

from . import forms, models


logger = logging.getLogger('django')


class SubmissionView(LoginRequiredMixin,
                     GroupRestrictedView,
                     CompleteProfileRequired,
                     CheckClosingDateMixin,
                     CreateView):
    template_name = 'abstract/submit.html'
    form_class = forms.AbstractForm
    success_url = '/profile/'
    context_object_name = 'instance'
    model = models.Abstract
    group_names = (UserGroups.SUBMITTER,)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_success_url(self):
        instance = self.object
        messages.success(
            self.request,
            "Submitted abstract with title <strong>'{}'</strong>.".format(
                instance.title
        ))
        return super().get_success_url()
    

class EditSubmissionView(LoginRequiredMixin,
                         GroupRestrictedView,
                         CompleteProfileRequired,
                         CheckClosingDateMixin,
                         UpdateView):
    template_name = 'abstract/edit.html'
    form_class = forms.AbstractForm
    success_url = '/profile/'
    slug_field = 'id'
    pk_url_kwarg = 'id'
    context_object_name = 'instance'
    model = models.Abstract
    group_names = (UserGroups.SUBMITTER,)
    
    def dispatch(self, request, *args, **kwargs):
        if self.get_object().submitter != request.user:
            raise Http404()

        closed = models.PresentationCategory.get_closed_categories()
        abstract = self.get_object()
        abstract_closed = []
        for category in abstract.categories.all():
            if category in closed:
                abstract_closed.append(category)
        if abstract_closed:
            messages.warning(
                request,
                "\"{}\" cannot be edited because submission has been closed "
                "for the following categories: {}.".format(
                    '<b>{}</b>'.format(abstract.title),
                    ', '.join(['<b>{}</b>'.format(c.text) for c in abstract_closed])
                )
            )
            return redirect("account:profile")

        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_success_url(self):
        instance = self.get_object()
        messages.success(
            self.request,
            "Updated abstract with title <strong>'{}'</strong>.".format(
                instance.title
        ))
        return super().get_success_url()


class DeleteSubmissionView(LoginRequiredMixin,
                           GroupRestrictedView,
                           CompleteProfileRequired,
                           CheckClosingDateMixin,
                           DeleteView):
    model = models.Abstract
    success_url = '/profile/'
    slug_field = 'id'
    pk_url_kwarg = 'id'
    context_object_name = 'instance'
    template_name = 'abstract/delete.html'
    group_names = (UserGroups.SUBMITTER,)
    
    def dispatch(self, request, *args, **kwargs):
        if self.get_object().submitter != request.user:
            raise Http404()

        closed = models.PresentationCategory.get_closed_categories()
        abstract = self.get_object()
        abstract_closed = []
        for category in abstract.categories.all():
            if category in closed:
                abstract_closed.append(category)
        if abstract_closed:
            messages.warning(
                request,
                "\"{}\" cannot be deleted because submission has been closed "
                "for the following categories: {}.".format(
                    '<b>{}</b>'.format(abstract.title),
                    ', '.join(['<b>{}</b>'.format(c.text) for c in abstract_closed])
                )
            )
            return redirect("account:profile")

        return super().dispatch(request, *args, **kwargs)
        
    def get_success_url(self):
        instance = self.get_object()
        messages.success(
            self.request,
            "Deleted abstract with title <strong>'{}'</strong>.".format(
                instance.title
        ))
        return super().get_success_url()


class AbstractDetailView(LoginRequiredMixin, GroupRestrictedView, DetailView):
    model = models.Abstract
    group_names = (UserGroups.ASSIGNER,
                   UserGroups.CONFERENCE_CHAIR,)
    template_name = 'abstract/abstract_detail.html'
    slug_field = 'id'
    pk_url_kwarg = 'id'
    context_object_name = 'abstract'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if UserGroups.CONFERENCE_CHAIR.value \
                in self.request.user.profile.group_names:
            if self.request.GET.get("show_demographics", False):
                context['show_demographics'] = True
        return context

abstract/templates/abstract/abstract.html
<div class="abstract-detail" id="{{ abstract.id }}-detail">
  <h2>{{ abstract.title }}</h2>

  {% if CHAIR_GROUP in request.user.profile.group_names %}
    <hr>
    <a class="btn btn-outline-danger mt-1"
       href="{% url 'abstract:abstract_summary' abstract.id %}?show_demographics=True">
      Show demographics
    </a>
    <a class="btn btn-outline-danger mt-1"
       href="{% url 'abstract:abstract_summary' abstract.id %}">
      Hide demographics
    </a>
    <hr>
  {% endif %}

  <p>{{ abstract.text }}</p>
  <p><strong>Submitted by:</strong> {{ abstract.submitter.profile.display_name }}</p>
  <p><strong>Contribution:</strong> {{ abstract.contribution }}</p>
  <p>
    <strong>Contributing authors:</strong>
      {% if not abstract.get_authors|length %}
       Not provided
      {% else %}
      <ul>
        {% for author in abstract.get_authors %}
          <li>{{ author }}</li>
        {% endfor %}
      </ul>
      {% endif %}
  </p>
  <p>
    <strong>Author affiliations:</strong>
      {% if not abstract.get_affiliations|length %}
       Not provided
      {% else %}
      <ul>
        {% for affiliation in abstract.get_affiliations %}
          <li>{{ affiliation }}</li>
        {% endfor %}
      </ul>
      {% endif %}
  </p>
  <p><strong>Categories:</strong> {{ abstract.categories.all|join:', ' }}</p>
  <p><strong>Keywords:</strong> {{ abstract.keywords.all|join:', ' }}</p>
  {% if CHAIR_GROUP in request.user.profile.group_names %}
    <p><strong>Overall score:</strong> {{ abstract.score|stringformat:"#.3g"|default:'-' }}</p>
  {% endif %}
</div>


{% if CHAIR_GROUP in request.user.profile.group_names %}
  {% if show_demographics %}
    <div class="abstract-demographics" id="{{ abstract.id }}-demographics">
      <hr>
      <h4>Demographic Information</h4>
      <p><strong>Career stage:</strong> {{ abstract.submitter.profile.career_stage }}</p>
      <p><strong>Gender:</strong> {{ abstract.submitter.profile.gender }}</p>
      <p><strong>State:</strong> {{ abstract.submitter.profile.state }}</p>
      <p><strong>Aboriginal or Torres Straight Islander:</strong> {{ abstract.submitter.profile.aboriginal_or_torres }}</p>
    </div>
  {% endif %}
{% endif %}

<div id="{{ abstract.id }}-reviews" class="abstract-reviews">
  <hr>
  <h2>Assignment summary</h2>
  <br>
  {% if not abstract.assignments.count %}
    <p class="text-muted">This abstract has not been assigned for review</p>
  {% else %}
    <div class="table-responsive">
      <table id="review-table" class="table table-hover display" style="width:100%">
        <thead>
          <th>Username</th>
          <th>Name</th>
          <th>Status</th>
          {% if CHAIR_GROUP in request.user.profile.group_names %}
            <th>Content</th>
            <th>Contribution</th>
            <th>Interest</th>
          {% endif %}
        </thead>
        <tbody>
          {% for assignment in abstract.assignments.all %}
            <tr>
              <td>{{ assignment.reviewer.username }}</td>
              <td>{{ assignment.reviewer.profile.full_name }}</td>
              <td>
                {% if assignment.status == DECLINED %}
                  Declined
                {% else %}
                  {{ assignment.status|capfirst }}
                {% endif %}
              </td>
              {% if CHAIR_GROUP in request.user.profile.group_names %}
                <td>{{ assignment.review.score_content|default:'-' }}</td>
                <td>{{ assignment.review.score_contribution|default:'-' }} </td>
                <td>{{ assignment.review.score_interest|default:'-' }} </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
</div>

<div id="{{ abstract.id }}-reviews" class="abstract-reviews">
  <hr>
  <h2>Comments</h2>
  <br>
  {% if not abstract.completed_assignments.count %}
    <p class="text-muted">This abstract has not been reviewed</p>
  {% else %}
    <div class="container">
      {% for assignment in abstract.accepted_assignments %}
        <div class="media">
          <i class="align-self-start mr-3 fa fa-check" style="font-size: 34px; color: #5cb85c"></i>
          <div class="media-body">
            <h5 class="mt-2">{{ assignment.reviewer.profile.full_name }}</h5>
              <div class="border-review hover-div">
                <p class="markdown">{{ assignment.review.text|default:'No comment provided' }}</p>
              </div>
          </div>
        </div>
        {% if forloop.counter0 < abstract.accepted_assignments.count %}
        <br>
        {% endif %}
      {% endfor %}
      {% for assignment in abstract.declined_assignments %}
        <div class="media">
          <i class="align-self-start mr-3 fa fa-times" style="font-size: 34px; color: #dd0c15"></i>
          <div class="media-body">
            <h5 class="mt-2">{{ assignment.reviewer.profile.full_name }}</h5>
            <div class="border-decline hover-div">
              <p class="markdown">{{ assignment.get_comment|default:'No comment provided' }} </p>
            </div>
          </div>
        </div>
        {% if forloop.counter0 < abstract.declined_assignments.count %}
        <br>
        {% endif %}
      {% endfor %}
    </div>
  {% endif %}
</div>

abstract/templates/abstract/abstract_detail.html
{% extends 'core/base.html' %}

{% block body %}
  <div id='{{ abstract.id }}-detail-container' class="container">
  {% include 'abstract/abstract.html' %}
  <br>

  <a class="btn btn-outline-dark mt-1"
     href="{% url 'account:profile' %}">
    Back
  </a>
</div>

{% endblock %}


{% block extra_scripts %}
<script type="text/javascript">
  $("document").ready(function() {
    let table = $("#review-table").DataTable({
      paging: false,
      dom: "",
    });
  });
</script>
{% endblock %}

abstract/templates/abstract/delete.html
{% extends 'core/base.html' %}

{% block body %}

  <div id='abstract-form-container' class="container">
    <h1>Withdraw abstract?</h1>
    <br><br>
    <form id='abstract-form' action="{% url 'abstract:delete_abstract' instance.id %}" method="post">
      {% csrf_token %}
      <p>Are you sure you want to withdraw your abstract titled
        <strong>"{{ instance.title }}"?</strong>
      </p>
      <br>
      <a class="btn btn-outline-dark" href="{% url 'account:profile' %}">Cancel</a>
      <button type="submit" class="btn btn-outline-danger">Withdraw</button>
    </form>
  </div>

{% endblock %}

abstract/templates/abstract/edit.html
{% extends 'core/base.html' %}

{% block body %}

  <div id='abstract-form-container' class="container">
    <h1>Edit your abstract</h1>
    You may edit your abstract freely up until the deadline. Further editing past
    this date will not be considered.
    <br><br>
    <form id='abstract-form' action="{% url 'abstract:edit_abstract' instance.id %}" method="post">
      {% csrf_token %}
      {% include 'core/bs4_form.html' %}
      <br>
      <button type="submit" class="btn btn-outline-dark">Submit</button>
      <a class="btn btn-outline-dark" href="{% url 'account:profile' %}">Cancel</a>
    </form>
  </div>

{% endblock %}

abstract/templates/abstract/submission.html
{% extends 'core/base.html' %}

{% block body %}

  <div id='abstract-form-container' class="container">
    <h1>Submit an abstract</h1>
    Please fill out the form below. You can also apply for travel funding
    from your profile.
    <br><br>
    <form id='abstract-form' action="{% url 'abstract:submit_abstract' %}" method="post">
      {% csrf_token %}
      {% include 'core/bs4_form.html' %}
      <br>
      <button type="submit" class="btn btn-outline-dark">Submit</button>
    </form>
  </div>

{% endblock %}

abstract/templates/abstract/submit.html
{% extends 'core/base.html' %}

{% block body %}

  <div id='abstract-form-container' class="container">
    <h1>Submit an abstract</h1>
    Please fill out the form below. You can also apply for travel funding
    from your profile.

    Abstracts will be selected for oral presentation on the basis of scientific quality
    (including innovation and importance) and breadth of interest to the ABACBS community.
    Those not selected will be offered a poster slot provided they meet a threshold of scientific quality.
    <br><br>
    <form id='abstract-form' action="{% url 'abstract:submit_abstract' %}" method="post">
      {% csrf_token %}
      {% include 'core/bs4_form.html' %}
      <br>
      <button type="submit" class="btn btn-outline-dark">Submit</button>
      <a class="btn btn-outline-dark" href="{% url 'account:profile' %}">Cancel</a>
    </form>
  </div>

{% endblock %}