ABACBSAbsSS/urls.py
from django.contrib import admin
from django.urls import path, include


handler403 = 'index.views.handler403'
handler404 = 'index.views.handler404'
handler500 = 'index.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('', include('account.urls', namespace='account')),
    path('', include('abstract.urls', namespace='abstract')),
]

abstract/urls.py
from django.urls import path, include

from . import views

app_name = 'abstract'

urlpatterns = [
    path('abstract/submit/', views.SubmissionView.as_view(), name='submit_abstract'),
    path('abstract/detail/<slug:id>/', views.AbstractDetailView.as_view(), name='abstract_summary'),
    path('abstract/edit/<slug:id>/', views.EditSubmissionView.as_view(), name='edit_abstract'),
    path('abstract/delete/<slug:id>/', views.DeleteSubmissionView.as_view(), name='delete_abstract'),
]

account/urls.py
from django.urls import path, include
from django.contrib.auth import logout

from . import views

app_name = 'account'

urlpatterns = [
    # ------ Login and Logout
    path('orcid/error/', views.orcid_login_error, name="orcid_login_error"),
    path('oauth/', include('social_django.urls', namespace='social'), name="social"),
    path('logout/', logout, name='logout'),
    path('login/orcid/', views.login_with_orcid, name='orcid_login'),
    path('login/staff/', views.staff_login, name='staff_login'),
    path('login/reset/', views.ResetPassword.as_view(), name="reset_password"),

    # ------ Profile
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/settings/', views.EditProfileView.as_view(), name="edit_profile"),
    path('profile/scholarship/', views.submitter.ScholarshipApplicationView.as_view(), name="scholarship_application"),
    path('profile/assign/<slug:id>/', views.assigner.assign_reviewers_view, name="assign_reviewers"),

    path('profile/download/abstracts/', views.chair.DownloadAbstracts.as_view(), name="download_abstracts"),
    path('profile/download/scholarships/', views.chair.DownloadScholarshipApplications.as_view(), name="download_scholarships"),
    path('profile/scholarships/', views.chair.ScholarshipListView.as_view(), name="scholarships"),
]

index/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('demographics/', views.plots, name='plots'),
]

core/models.py
import datetime

from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class TimeStampedModel(models.Model):
    """
    Represents a time stamped model updating the modification date everytime
    an instance is saved.
    """
    class Meta:
        abstract = True
        ordering = ['-creation_date']

    creation_date = models.DateField(
        default=datetime.date.today,
        verbose_name='Creation date',
    )
    modification_date = models.DateField(
        default=datetime.date.today,
        verbose_name='Modification date',
    )

    def save(self, *args, **kwargs):
        self.modification_date = datetime.date.today()
        return super().save(*args, **kwargs)

core/views.py
from django.shortcuts import render

core/templates/core/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ABACBS Abstract Submission</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="AbsSS">
    <meta name="author" content="Daniel C. Esposito">
    <meta name="keywords" content="abstract,submission system,abstract review,conference abstract review,conference">
{#    <link href="{% static 'core/google/fonts_icons.css' %}" rel="stylesheet" type="text/css">#}
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <link href="{% static 'core/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/select2/select2_4.0.5.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/fontawesome/fontawesome_5.1.0.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/core/base.css' %}" rel="stylesheet" type="text/css">
    <link rel="icon" type="image/x-icon" href="{% static 'core/core/small_logo.svg' %}">
  </head>

  <body>
    <!-- Header for screen width > 768 -->
    <header id="header">
      <a id="header-logo-wrapper" href="https://www.abacbs.org/" target="_blank">
        <img id="header-logo" src="{% static 'core/core/small_logo.svg' %}">
      </a>
      <div class="header-nav">
        <a class="nav-link" href="{% url 'index:index' %}">Home</a>
        {% if not request.user.is_authenticated %}
          <div class="nav-dropdown">
            <a class="nav-link" href="#">Login <i class="fa fa-caret-down"></i></a>
            <ul class="nav-dropdown-content zero-pad-ul">
              <li><a class="nav-link" href="#" data-toggle="modal" data-target="#orcid-login">Applicant</a></li>
              <li><a class="nav-link" href="{% url 'account:staff_login' %}">Staff</a></li>
            </ul>
          </div>
        {% else %}
          <div class="nav-dropdown">
            <a class="nav-link" href="#">Profile <i class="fa fa-caret-down"></i></a>
            <ul class="nav-dropdown-content zero-pad-ul">
              <li><a class="nav-link" href="{% url 'account:profile' %}">Dashboard</a></li>
              {% if request.user.groups.first.name == SUBMITTER_GROUP %}
                <li><a class="nav-link" href="{% url 'abstract:submit_abstract' %}">New abstract</a></li>
                <li><a class="nav-link" href="{% url 'account:scholarship_application' %}">Travel scholarship</a></li>
                <li><a class="nav-link" href="{% url 'account:edit_profile' %}">Settings</a></li>
              {% endif %}
              {% if request.user.groups.first.name == REVIEWER_GROUP %}
                <li><a class="nav-link" href="{% url 'account:edit_profile' %}">Settings</a></li>
              {% endif %}
              {% if request.user.groups.first.name == CHAIR_GROUP %}
                <li><a class="nav-link" href="{% url 'account:scholarships' %}">Scholarships</a></li>
              {% endif %}
              <li><a class="nav-link" href="{% url 'account:logout' %}">Logout</a></li>
            </ul>
          </div>
        {% endif %}
      </div>
    </header>


    <!-- Header for screen width <= 768 -->
    <div id="mobile-header">
      <img id="mobile-header-menu" class="menu-icon"
           src="{% static 'core/core/small_logo.svg' %}">
    </div>

    <!-- ORCID modal -->
    {% include 'index/orcid_login_modal.html' %}

    <!-- Sidebar for mobile devices -->
    <div id="sidebar">
      <div id="inner-sidebar">
        <img id="sidebar-logo" src="{% static 'core/core/small_logo.svg' %}">
        <hr>
        <ul class="zero-pad-ul">
          <li class="nav-link"><a class="hover-underline" href="{% url 'index:index' %}">Home</a></li>

          {% if not request.user.is_authenticated %}
            <li class="nav-link"><a class="hover-underline" href="">Login</a></li>
              <li class="nav-link indent"><a class="hover-underline" href="#" data-toggle="modal" data-target="#orcid-login">Applicant</a></li>
              <li class="nav-link indent"><a class="hover-underline" href="{% url 'account:staff_login' %}">Staff</a></li>
          {% else %}
            <li class="nav-link"><a class="hover-underline" href="">Profile</a></li>
              <li class="nav-link indent"><a class="hover-underline" href="{% url 'account:profile' %}">Dashboard</a></li>
              {% if request.user.groups.first.name == SUBMITTER_GROUP %}
                <li class="nav-link indent"><a class="hover-underline" href="{% url 'abstract:submit_abstract' %}">New abstract</a></li>
                <li class="nav-link indent"><a class="hover-underline" href="{% url 'account:scholarship_application' %}">Travel scholarship</a></li>
                <li class="nav-link indent"><a class="hover-underline" href="{% url 'account:edit_profile' %}">Settings</a></li>
              {% endif %}
              {% if request.user.groups.first.name == REVIEWER_GROUP %}
                <li class="nav-link indent"><a class="hover-underline" href="{% url 'account:edit_profile' %}">Settings</a></li>
              {% endif %}
              {% if request.user.groups.first.name == CHAIR_GROUP %}
                <li class="nav-link indent"><a class="hover-underline" href="{% url 'account:scholarships' %}">Scholarships</a></li>
              {% endif %}
              <li class="nav-link indent"><a class="hover-underline" href="{% url 'account:logout' %}">Logout</a></li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="container-fluid border-bottom header-border"></div>

    {% include 'core/messages.html' %}

    <!-- Main content -->
    <div id="middle-content" class="container-fluid" style="width: 75%;">
      {% block body %}{% endblock %}
    </div>

    <div class="container-fluid border-top footer-border"></div>

    <!-- Footer is not sticky and shift when main content grows -->
    <footer id="footer">
      <p id="footer-links">
        <a href="https://twitter.com/abacbs?lang=en" target="_blank">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="https://github.com/daniaki/ABACBSAbsSS" target="_blank">
          <i class="fab fa-github"></i>
        </a>
      </p>
      <p id="footer-info">
        Australian Bioinformatics and Computational Biology Society Inc.
        <br>
        <a href="tel:+61393452627" class="text-like">+61 3 9345 2627</a>
        <br>
        <a href="mailto:committee@abacbs.org" class="text-like">committee@abacbs.org</a>
      </p>
    </footer>

    <!-- Scripts -->
    <!-- Ask user confirmation to remove themself as an instance admin -->
    <!-- This needs to be here in order to record the user pk from django -->
    <script src="{% static 'core/jquery/jquery-3.3.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/jquery/jquery-ui.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/bootstrap/popper_1.12.9.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/bootstrap/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/select2/select2_4.0.5.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/datatables/datatables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/fontawesome/fontawesome_5.1.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/vue/vue.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/showdown/showdown.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/core/base.js' %}" type="text/javascript"></script>
    {% block extra_scripts %}
    {% endblock %}
  </body>
</html>

core/templates/core/bs4_form.html
{% load static %}
{% load form_tags %}
{% load i18n %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  {% is_checkbox field as is_checkbox %}

  <div class="form-group {{ field.label|lower }}-group">

    {{ field.label_tag }}{% if field.field.required %}*{% endif %}
    <label for="{{ field.id_for_label }}"></label>
    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}

    {% if form.is_bound %}
      {% if field.errors or not field.errors and form.non_field_errors %}

        {% if is_checkbox %}
          {% add_css_class field "is-invalid" %}
        {% else %}
          {% add_css_class field "form-control is-invalid" %}
        {% endif %}

        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}

      {% else %}
        {% if is_checkbox %}
          {% add_css_class field "is-valid" %}
        {% else %}
          {% add_css_class field "form-control is-valid" %}
        {% endif %}
      {% endif %}
    {% else %}
      {% if is_checkbox %}
        {% add_css_class field "" %}
      {% else %}
        {% add_css_class field "form-control" %}
      {% endif %}
    {% endif %}
  </div>

{% endfor %}

core/templates/core/messages.html
<div class="container messages pt-4">
  {% if messages %}
    {% for message in messages %}
      {% if 'success' in message.tags %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <h4 class="alert-heading">Success!</h4>
          <hr style="width: 98%">
          <p>{{ message|safe }}</p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}

      {% if 'error' in message.tags %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <h4 class="alert-heading text-center">Error!</h4>
          <hr style="width: 98%">
          <p class="pl-4">{{ message|safe }}</p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}

      {% if 'warning' in message.tags %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <h4 class="alert-heading">Warning!</h4>
          <hr style="width: 98%">
          <p class="pl-4">{{ message|safe }}</p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}

      {% if 'info' in message.tags %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
          <h4 class="alert-heading text-center">Information</h4>
          <hr style="width: 98%">
          <p class="pl-4">{{ message|safe }}</p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}
</div>