ABACBSAbsSS/urls.py
from django.contrib import admin
from django.urls import path, include


handler403 = 'index.views.handler403'
handler404 = 'index.views.handler404'
handler500 = 'index.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('', include('account.urls', namespace='account')),
    path('', include('abstract.urls', namespace='abstract')),
]

account/urls.py
from django.urls import path, include
from django.contrib.auth import logout

from . import views

app_name = 'account'

urlpatterns = [
    # ------ Login and Logout
    path('orcid/error/', views.orcid_login_error, name="orcid_login_error"),
    path('oauth/', include('social_django.urls', namespace='social'), name="social"),
    path('logout/', logout, name='logout'),
    path('login/orcid/', views.login_with_orcid, name='orcid_login'),
    path('login/staff/', views.staff_login, name='staff_login'),
    path('login/reset/', views.ResetPassword.as_view(), name="reset_password"),

    # ------ Profile
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/settings/', views.EditProfileView.as_view(), name="edit_profile"),
    path('profile/scholarship/', views.submitter.ScholarshipApplicationView.as_view(), name="scholarship_application"),
    path('profile/assign/<slug:id>/', views.assigner.assign_reviewers_view, name="assign_reviewers"),

    path('profile/download/abstracts/', views.chair.DownloadAbstracts.as_view(), name="download_abstracts"),
    path('profile/download/scholarships/', views.chair.DownloadScholarshipApplications.as_view(), name="download_scholarships"),
    path('profile/scholarships/', views.chair.ScholarshipListView.as_view(), name="scholarships"),
]

index/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('demographics/', views.plots, name='plots'),
]

index/templates/index/index.html
{% extends "core/base.html" %}
{% load static %}

{% block body %}

  <img id='big-logo' src="{% static "core/core/large_logo.svg" %}" style="position: relative; left: -15px">
  <hr>

  <div class="alert alert-warning" role="alert">
    <strong>Attention!</strong>
    <p>Additional ABACBS Conference and COMBINE Symposium poster submissions will be open between October 24th 12:01am until November 7th 11:59pm.</p>
  </div>

  <h1>Abstract submission guide</h1>
  <ol>
    <li>Log in via <a href="{% url 'account:orcid_login' %}">ORCID</a></li>
    <li>
      Once completed you will be directed to your profile settings page.
      You will need to provide us with a few extra details before proceeding.
    </li>
    <li>
      Once completed, you will be redirected to your dashboard. Click the
      <strong><i class="fa fa-plus"></i></strong> sign
      next to <strong>'Your abstracts'</strong> to begin a new submission.
    </li>
    <li>
      A submission consists of several required fields:
        <ul>
          <li>Title (limited to 30 words or less).</li>
          <li>Abstract content (limited to 250 words or less).</li>
          <li>Your contribution to the research described (limited to 100 words or less).</li>
          <li>All contributing authors including yourself.</li>
          <li>The primary affiliations of all contributing authors.</li>
          <li>Keywords you wish to associate with the abstract.</li>
          <li>One or more presentation catorgies you wish to apply under.</li>
        </ul>
    </li>
    <li>
      Upon submitting a new abstract you will be redirected to your dashboard. Here
      you can edit (<i class="fa fa-edit"></i>) or delete (<i class="fa fa-trash"></i>)
      existing abstracts up until the deadline.
    </li>
  </ol>
  <hr>

  <h1>Travel scholarship application guide</h1>
  <ol>
    <li>
      You can apply for a travel scholarship at any time by
      opening the profile menu in the top right (or sidebar for mobile users)
      and clicking on <a href="{% url 'account:scholarship_application' %}">Travel Scholarship</a>.
    </li>
    <li>
      You will need to fill in a few required fields:
        <ul>
          <li>Reason for application (limited to 200 words or less).</li>
          <li>Indication of other external sources of funding.</li>
          <li>If applicable, details of your other external sources of funding.</li>
        </ul>
    </li>
    <li>
      Upon successfull submission to your dashboard. You can revist the scholarship
      application page at any time to edit or delete your application up until the
      deadline.
    </li>
  </ol>


  <hr>

  <h1 id="demographic-plots">Demographic Information</h1>
  <p>
    The plots below show the demographic information relating to four
    categories: the applicant's identified <strong>gender</strong>,
    <strong>career stage</strong>, <strong>state of residence</strong>
    and whether they indentify as an <strong>Aboriginal or Torres Straight Islander</strong>.

    This information is collected on a <strong>per-abstract basis</strong>.
  </p>

  <div class="container" id="plots" style="margin-top: 12px">
    <div class="row">
      <div class="col-12 col-xl-6">
        <div id="gender-plot"></div>
      </div>

      <div class="col-12 col-xl-6">
        <div id="stage-plot"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-xl-6">
        <div id="aot-plot"></div>
      </div>

      <div class="col-12 col-xl-6">
        <div id="state-plot"></div>
      </div>
    </div>
  </div>

{% endblock %}


{% block extra_scripts %}
  <script src="{% static 'core/plotly/plotly-latest.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'core/core/plots.js' %}" type="text/javascript"></script>
{% endblock %}

index/templates/index/orcid.html
<!-- Modal -->
<div class="modal fade" id="orcid-login" tabindex="-1" role="dialog" aria-labelledby="orcidModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="orcidModal">Log in with ORCID</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          ORCID is an independent non-profit effort to provide an open registry of unique researcher
          identifiers and open services to link research activities and organizations to these
          identifiers. Learn more at <a href="https://orcid.org/">orcid.org</a>.
        </p>
        <button id="connect-orcid-button" onclick="openORCID()">
          <img id="orcid-id-logo" src="https://orcid.org/sites/default/files/images/orcid_24x24.png" width='24' height='24' alt="ORCID logo"/>
          Create or Connect your ORCID iD
        </button>
      </div>
    </div>
  </div>
</div>

index/templates/index/orcid_login_modal.html
<!-- Modal -->
<div class="modal fade" id="orcid-login" tabindex="-1" role="dialog" aria-labelledby="orcidModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="orcidModal">Log in with ORCID</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          ORCID is an independent non-profit effort to provide an open registry of unique researcher
          identifiers and open services to link research activities and organizations to these
          identifiers. Learn more at <a href="https://orcid.org/">orcid.org</a>.
        </p>
        <button id="connect-orcid-button" onclick="openORCID()">
          <img id="orcid-id-logo" src="https://orcid.org/sites/default/files/images/orcid_24x24.png" width='24' height='24' alt="ORCID logo"/>
          Create or Connect your ORCID iD
        </button>
      </div>
    </div>
  </div>
</div>

index/templates/index/plots.html
{% extends "core/base.html" %}
{% load static %}

{% block body %}
  <h1 id="demographic-plots">Demographic Information</h1>
  <p>
    The plots below show the demographic information relating to four
    categories: the applicant's identified <strong>gender</strong>,
    <strong>career stage</strong>, <strong>state of residence</strong>
    and whether they indentify as an <strong>Aboriginal or Torres Straight Islander</strong>.

    This information is collected on a <strong>per-abstract basis</strong>.
  </p>
  <div class="container mt-4" id="plots">
    <div class="row">
      <div class="col-12 col-xl-6">
        <div id="gender-plot"></div>
      </div>

      <div class="col-12 col-xl-6">
        <div id="stage-plot"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-xl-6">
        <div id="aot-plot"></div>
      </div>

      <div class="col-12 col-xl-6">
        <div id="state-plot"></div>
      </div>
    </div>
  </div>

{% endblock %}


{% block extra_scripts %}
  <script src="{% static 'core/plotly/plotly-latest.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'core/core/plots.js' %}" type="text/javascript"></script>
{% endblock %}